### PR TITLE
Adopt native async/await 🎉

### PR DESCRIPTION
**Pull request by kirilltitov**
- [x] Phase 1: add async/await interface
- [x] Phase 2: abandon NIO interface (extract it to a dedicated package, to be more precise; between phases 5 and 6, I guess)
- [x] Phase 3: do something about tests (XCTest doesn't support async/await yet)
- [x] Phase 4: update the readme
- [x] Phase 5: pick a new epigram for readme
- [ ] ~Phase 6: wait until Swift 6 (?) is released~

### CODE REVIEW

**Comment by kirilltitov** [comment]
Example:

```swift
import _Concurrency
import FDB

runAsyncAndBlock {
    do {
        let fdb = FDB()
        try fdb.connect()
        let subspace = FDB.Subspace("testsubspace")
        let key1 = subspace["asynctest"]
        let key2 = subspace["asynctest2"]
        let result = await try fdb.withTransaction { (tr: AnyFDBTransaction) -> String in
            await try tr.set(key: key1, value: "it works!".bytes, commit: false)
            await try tr.set(key: key2, value: "and this one too".bytes, commit: false)
            async let result1 = await try tr.get(key: key1, snapshot: false, commit: false)?.string ?? "NOES1"
            async let result2 = await try tr.get(key: key2, snapshot: false, commit: false)?.string ?? "NOES2"
            let result = await try "\(result1) >> \(result2)"
            await try tr.commit()
            return result
        }
        dump(result)
    } catch {
        print(error)
    }
}

public extension String {
    var bytes: Bytes {
        Bytes(self.utf8)
    }
}

internal extension Array where Element == Byte {
    @usableFromInline
    func cast<R>() throws -> R {
        guard MemoryLayout<R>.size == self.count else {
            throw FDB.Error.unexpectedError(
                """
                Memory layout size for result type '\(R.self)' (\(MemoryLayout<R>.size) bytes) does \
                not match with given byte array length (\(self.count) bytes)
                """
            )
        }
        return self.withUnsafeBytes {
            $0.baseAddress!.assumingMemoryBound(to: R.self).pointee
        }
    }

    @usableFromInline
    var length: Int32 {
        return numericCast(self.count)
    }

    @usableFromInline
    var string: String {
        return String(bytes: self, encoding: .ascii)!
    }
}
```

outputs:

```
- "it works! >> and this one too"
Program ended with exit code: 0
```

**Comment by dimitribouniol** [comment]
This is exciting!

Since this is going down the rabbit hole of a major version bump, some wish-list items I’ve had (that you are more than welcome to ignore 😅):
- Eliminate the need to cast the results of any method to pick the correct variant - command clicking FDBSwift members to find the one that’s being used is a bit of a nightmare in Xcode 😅
- Clean up `try`’s and asynchronous actions that don’t throw or ever return futures, and can safely be dispatched without waiting on the future of a previous action (ie. set) — maybe this is less of a concern with a async/await, but it made dealing with futures in NIO cumbersome.
- Make byte manipulation more consistent — I actually made a [library called `Bytes`](https://github.com/mochidev/Bytes) inspired by how you used `Bytes`, and how it was used in other server-side swift packages that you could make use of directly (as a potential dependency), or indirectly (by copying in the sources directly as internal extensions). It complements FDBSwift quite nicely, especially when preparing contents for FDB values.

**Comment by kirilltitov** [comment]
Great input!

1. Not sure I got your point here, you want a series of overloaded methods which return `String?`, `Int?` etc? I'm afraid it might inflate the API greatly, and Xcode will definitely choke :) Or did you mean a universal `T?` method (along with `Bytes?` one) which would cast everything automatically? This one is worth trying out.
2. Yes, you are right. All write operations are non-blocking (and non-suspending either) and non-throwing internally, the only reason for `async/try` is `commit: Bool` argument, which I want to eliminate for good (thus, `AnyFDB` API will be for one-shot autocommitted operations, and `AnyFDBTransaction` API will be for complex operations with explicit commit in the end, as intended originally, but I didn't emphasize it in readme/docblocks enough).
3. Wow, that's actually neat! Will certainly take a look.

Of course, we will have to wait until concurrency roadmap to be completely released and stable (I think we will have it after WWDC with Swift 6), and FDBSwift 5 will release when I'm comfortable with the API (I have a few services that utilize it heavily, so it will be a good test drive) AND when next FDB is released (optionally, but very desirable).

(In fact, I want to sync FDBSwift major version with FDB major version, but I'm still not sure about it)

**Comment by dimitribouniol** [comment]
Re: 1, I more meant about the fact that there were like 10 different set methods, necessitating as Void all over the place. Same for the other class of methods haha.

For 2, that dichotomy between AnyFDB and AnyFDBTransaction would probably solve 1) for the most part.

That said, having some decode generics/overloads on get value, and encode generics on set value might be pretty nifty, but that could also be a separate package for the most part so this one is lean and mean 😉

(No clue if you wanted to enable the new GitHub discussions feature on this repo so I don’t further sidetrack this PR with ideas haha - for the time being, I’m going to bed since it is 2 am here)

**Comment by kirilltitov** [comment]
We're back on track! There is async/await support for XCTest in Linux (however, in `main` only for now) and I have a polyfill for macOS (what a disaster release, good lord).

**Comment by kirilltitov** [comment]
Ho-ho-ho, would you just look at that, the sexiest thing I've seen in a long time. Now it's just a matter of rewriting the readme and we have a release candidate (still waiting for macOS Monterey and proper Linux XCTest support, I don't really like [that pornography](https://github.com/kirilltitov/FDBSwift/blob/fba59498d124d80d64d14d0d5509f614817fec25/Tests/FDBTests/FDBTests.swift#L5-L57) in FDBTests.swift)

Снимок экрана 2021-09-28 в 15 58 15

**Pull request merged**
